export {default as loginBg} from "./img/loginBg.jpg"
export {default as avatar } from "./img/avatar.png"
export {default as delivery} from "./img/delivery.png"
export {default as heroBg} from "./img/heroBg.png"
export { default as logo } from "./img/logo.png"
export { default as bill} from "./img/bill.png"
export {default as mango} from "./img/mango.jpg"